def genre_scores(tags):
    scores = {}
    for tag in tags:
        if tag in mapping:
            for genre in mapping[tag]:
                if not genre in scores:
                    scores[genre] = 0
                scores[genre] += 1
    return scores

genres = ['Action', 'Adventure', 'Casual', 'Indie', 'Massively Multiplayer', 'Racing', 'RPG', 'Simulation', 'Sports', 'Strategy']

mapping = {
    "2d": [],
    "2d fighter": ["action"],
    "4 player local": [],
    "action": ["action"],
    "action rpg": ["action", "rpg"],
    "adventure": ["adventure"],
    "anime": [],
    "arcade": ["casual"],
    "atmospheric": [],
    "building": [],
    "card game": [],
    "cartoon": [],
    "cartoony": [],
    "casual": ["casual"],
    "character customization": [],
    "city builder": ["simulation", "strategy"],
    "classic": [],
    "co-op": [],
    "comedy": [],
    "competitive": [],
    "controller": [],
    "cute": [],
    "dark": [],
    "dark fantasy": [],
    "dating sim": [],
    "difficult": [],
    "dungeon crawler": ["action", "rpg"],
    "early access": [],
    "economy": [],
    "fps": ["action"],
    "family friendly": [],
    "fantasy": [],
    "fast-paced": [],
    "female protagonist": [],
    "fighting": ["action"],
    "first-person": ["action"],
    "free to play": [],
    "funny": [],
    "futuristic": [],
    "gamemaker": [],
    "great soundtrack": [],
    "horror": ["adventure"],
    "indie": ["indie"],
    "kickstarter": [],
    "local co-op": [],
    "local multiplayer": [],
    "lovecraftian": [],
    "moba": ["strategy"],
    "management": ["simulation"],
    "mars": [],
    "military": [],
    "mod": [],
    "moddable": [],
    "multiplayer": [],
    "multiple endings": [],
    "mystery": [],
    "online co-op": [],
    "otome": [],
    "parody": [],
    "perma death": [],
    "pixel graphics": [],
    "platformer": [],
    "puzzle": ["casual"],
    "pvp": [],
    "rpg": ["rpg"],
    "rts": ["strategy"],
    "real-time with pause": ["rpg"],
    "realistic": [],
    "replay value": [],
    "resource management": ["strategy"],
    "retro": [],
    "rogue-like": [],
    "rogue-lite": [],
    "romance": [],
    "sandbox": [],
    "sci-fi": [],
    "score attack": [],
    "shooter": ["action"],
    "simulation": ["simulation"],
    "singleplayer": [],
    "space": [],
    "sports": ["sports"],
    "story rich": [],
    "strategy": ["strategy"],
    "survival": [],
    "swordplay": [],
    "tactical": [],
    "team-based": [],
    "tower defense": [],
    "trading": [],
    "trading card game": [],
    "turn-based": [],
    "turn-based combat": [],
    "visual novel": [],
    "war": [],
    "zombies": [],
    "e-sports": []
}